// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-colaboradores.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/helpers.ts
function requireUserClient(ctx) {
  if (!ctx.isAuthenticated()) return null;
  return supabaseForUser(ctx);
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to RH Insights to use this tool." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-colaboradores.ts
var list_colaboradores_default = defineTool({
  name: "list_colaboradores",
  title: "Listar colaboradores",
  description: "List employees (colaboradores) with optional filters by status, department and name search. Returns role, department, hire date and status.",
  inputSchema: {
    status: z.string().optional().describe("Filter by status, e.g. 'Ativo' or 'Desligado'."),
    departamento: z.string().optional().describe("Filter by department name (exact match)."),
    search: z.string().optional().describe("Case-insensitive partial match on the employee name."),
    limit: z.number().int().optional().describe("Maximum rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, departamento, search, limit }, ctx) => {
    const supabase = requireUserClient(ctx);
    if (!supabase) return unauthenticated();
    let query = supabase.from("colaboradores").select(
      "id, nome, cargo, departamento, tipo_colaborador, status, is_lider, data_admissao, data_desligamento, filial_id"
    ).order("nome").limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (status) query = query.eq("status", status);
    if (departamento) query = query.eq("departamento", departamento);
    if (search) query = query.ilike("nome", `%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, colaboradores: data ?? [] });
  }
});

// src/lib/mcp/tools/list-afastamentos.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var list_afastamentos_default = defineTool2({
  name: "list_afastamentos",
  title: "Listar afastamentos",
  description: "List employee leaves/absences (afastamentos) in a date range, including type, start and end date and days absent.",
  inputSchema: {
    data_inicio: z2.string().optional().describe("Start of the range as YYYY-MM-DD (filters on data_inicio)."),
    data_fim: z2.string().optional().describe("End of the range as YYYY-MM-DD (filters on data_inicio)."),
    tipo: z2.string().optional().describe("Filter by leave type."),
    limit: z2.number().int().optional().describe("Maximum rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ data_inicio, data_fim, tipo, limit }, ctx) => {
    const supabase = requireUserClient(ctx);
    if (!supabase) return unauthenticated();
    let query = supabase.from("afastamentos").select("id, tipo, data_inicio, data_fim, dias_afastados, observacoes, colaboradores(nome, departamento)").order("data_inicio", { ascending: false }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (data_inicio) query = query.gte("data_inicio", data_inicio);
    if (data_fim) query = query.lte("data_inicio", data_fim);
    if (tipo) query = query.eq("tipo", tipo);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, afastamentos: data ?? [] });
  }
});

// src/lib/mcp/tools/list-desligamentos.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var list_desligamentos_default = defineTool3({
  name: "list_desligamentos",
  title: "Listar desligamentos",
  description: "List employee terminations (desligamentos) in a date range, including reason, date and severance cost. Useful for turnover analysis.",
  inputSchema: {
    data_inicio: z3.string().optional().describe("Start of the range as YYYY-MM-DD."),
    data_fim: z3.string().optional().describe("End of the range as YYYY-MM-DD."),
    motivo: z3.string().optional().describe("Filter by termination reason."),
    limit: z3.number().int().optional().describe("Maximum rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ data_inicio, data_fim, motivo, limit }, ctx) => {
    const supabase = requireUserClient(ctx);
    if (!supabase) return unauthenticated();
    let query = supabase.from("desligamentos").select("id, data_desligamento, motivo, custo_rescisao, observacoes, colaboradores(nome, cargo, departamento)").order("data_desligamento", { ascending: false }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (data_inicio) query = query.gte("data_desligamento", data_inicio);
    if (data_fim) query = query.lte("data_desligamento", data_fim);
    if (motivo) query = query.eq("motivo", motivo);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, desligamentos: data ?? [] });
  }
});

// src/lib/mcp/tools/list-treinamentos-eventos.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var list_treinamentos_eventos_default = defineTool4({
  name: "list_treinamentos_eventos",
  title: "Listar treinamentos e eventos",
  description: "List trainings (treinamentos) and institutional events (eventos) in a date range, with workload, capacity and completion status.",
  inputSchema: {
    data_inicio: z4.string().optional().describe("Start of the range as YYYY-MM-DD."),
    data_fim: z4.string().optional().describe("End of the range as YYYY-MM-DD."),
    limit: z4.number().int().optional().describe("Maximum rows per collection (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ data_inicio, data_fim, limit }, ctx) => {
    const supabase = requireUserClient(ctx);
    if (!supabase) return unauthenticated();
    const max = Math.min(Math.max(limit ?? 50, 1), 200);
    let trainings = supabase.from("treinamentos").select("id, nome, descricao, data_realizacao, carga_horaria, tipo, vagas_totais, finalizado").order("data_realizacao", { ascending: false }).limit(max);
    let events = supabase.from("eventos").select("id, nome, descricao, data_evento, tipo, capacidade, finalizado").order("data_evento", { ascending: false }).limit(max);
    if (data_inicio) {
      trainings = trainings.gte("data_realizacao", data_inicio);
      events = events.gte("data_evento", data_inicio);
    }
    if (data_fim) {
      trainings = trainings.lte("data_realizacao", data_fim);
      events = events.lte("data_evento", data_fim);
    }
    const [trainingsResult, eventsResult] = await Promise.all([trainings, events]);
    if (trainingsResult.error) return errorResult(trainingsResult.error.message);
    if (eventsResult.error) return errorResult(eventsResult.error.message);
    return jsonResult({
      treinamentos: trainingsResult.data ?? [],
      eventos: eventsResult.data ?? []
    });
  }
});

// src/lib/mcp/tools/hr-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.25.76";
var hr_summary_default = defineTool5({
  name: "hr_summary",
  title: "Resumo de indicadores de RH",
  description: "Return headcount, hires, terminations, turnover rate and absence days for a period, broken down by department.",
  inputSchema: {
    data_inicio: z5.string().describe("Period start as YYYY-MM-DD."),
    data_fim: z5.string().describe("Period end as YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ data_inicio, data_fim }, ctx) => {
    const supabase = requireUserClient(ctx);
    if (!supabase) return unauthenticated();
    const [employees, hires, terminations, leaves] = await Promise.all([
      supabase.from("colaboradores").select("departamento, status, is_lider, tipo_colaborador"),
      supabase.from("contratacoes").select("id, data_contratacao").gte("data_contratacao", data_inicio).lte("data_contratacao", data_fim),
      supabase.from("desligamentos").select("id, motivo, data_desligamento").gte("data_desligamento", data_inicio).lte("data_desligamento", data_fim),
      supabase.from("afastamentos").select("id, tipo, dias_afastados, data_inicio").gte("data_inicio", data_inicio).lte("data_inicio", data_fim)
    ]);
    const failure = [employees, hires, terminations, leaves].find((result) => result.error);
    if (failure?.error) return errorResult(failure.error.message);
    const rows = employees.data ?? [];
    const active = rows.filter((row) => row.status === "Ativo");
    const byDepartment = {};
    for (const row of active) {
      const key = row.departamento || "Nao informado";
      byDepartment[key] = (byDepartment[key] ?? 0) + 1;
    }
    const hiresCount = hires.data?.length ?? 0;
    const terminationsCount = terminations.data?.length ?? 0;
    const headcount = active.length;
    const turnoverRate = headcount > 0 ? (hiresCount + terminationsCount) / 2 / headcount * 100 : 0;
    const absenceDays = (leaves.data ?? []).reduce((total, row) => total + (row.dias_afastados ?? 0), 0);
    const reasons = {};
    for (const row of terminations.data ?? []) {
      const key = row.motivo || "Nao informado";
      reasons[key] = (reasons[key] ?? 0) + 1;
    }
    return jsonResult({
      periodo: { data_inicio, data_fim },
      headcount_ativo: headcount,
      total_cadastrados: rows.length,
      lideres: active.filter((row) => row.is_lider).length,
      contratacoes: hiresCount,
      desligamentos: terminationsCount,
      turnover_percentual: Number(turnoverRate.toFixed(2)),
      dias_afastamento: absenceDays,
      afastamentos: leaves.data?.length ?? 0,
      headcount_por_departamento: byDepartment,
      motivos_desligamento: reasons
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "liqvudyxgceqpqkykgmp";
var mcp_default = defineMcp({
  name: "rh-insights",
  title: "RH Insights",
  version: "0.1.0",
  instructions: "People analytics tools for RH Insights. Use `hr_summary` for headcount, hires, terminations, turnover and absence indicators over a period; `list_colaboradores` for employee records; `list_afastamentos` for leaves; `list_desligamentos` for terminations; `list_treinamentos_eventos` for trainings and institutional events. All dates use the YYYY-MM-DD format.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [hr_summary_default, list_colaboradores_default, list_afastamentos_default, list_desligamentos_default, list_treinamentos_eventos_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
